 

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const DocumentId = IDL.Text;
export const AssignmentId = IDL.Nat;
export const Time = IDL.Int;
export const Assignment = IDL.Record({
  'id' : AssignmentId,
  'assignedAt' : Time,
  'assignedTo' : IDL.Text,
  'documentId' : DocumentId,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Document = IDL.Record({
  'id' : DocumentId,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'uploadedAt' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'assignDocument' : IDL.Func([DocumentId, IDL.Text], [Assignment], []),
  'getAllDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
  'getAssignmentsForUser' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Assignment)],
      ['query'],
    ),
  'getDocument' : IDL.Func([DocumentId], [Document], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const DocumentId = IDL.Text;
  const AssignmentId = IDL.Nat;
  const Time = IDL.Int;
  const Assignment = IDL.Record({
    'id' : AssignmentId,
    'assignedAt' : Time,
    'assignedTo' : IDL.Text,
    'documentId' : DocumentId,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Document = IDL.Record({
    'id' : DocumentId,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'uploadedAt' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'assignDocument' : IDL.Func([DocumentId, IDL.Text], [Assignment], []),
    'getAllDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
    'getAssignmentsForUser' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Assignment)],
        ['query'],
      ),
    'getDocument' : IDL.Func([DocumentId], [Document], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };